
on:

  push:
    branches:
      - main

env:

  node-version: 22

jobs:

  setup:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v4
      -
        id: cache
        uses: actions/cache@v4
        with:
          key: pnpm-lock--${{hashFiles('pnpm-lock.yaml')}}
          path: node_modules
          restore-keys: pnpm-lock--
          lookup-only: true
      -
        if: steps.cache.outputs.cache-hit != 'true'
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: true

  compile:
    runs-on: ubuntu-latest
    needs:
      - setup
    steps:
      -
        uses: actions/checkout@v4
      -
        uses: actions/cache/restore@v4
        with:
          key: pnpm-lock--${{hashFiles('pnpm-lock.yaml')}}
          path: node_modules
          fail-on-cache-miss: true
      -
        uses: actions/setup-node@v4
        with:
          node-version: ${{env.node-version}}
      -
        run: npx -- tsc

  linting:
    runs-on: ubuntu-latest
    needs:
      - setup
    steps:
      -
        uses: actions/checkout@v4
      -
        uses: actions/cache/restore@v4
        with:
          key: pnpm-lock--${{hashFiles('pnpm-lock.yaml')}}
          path: node_modules
          fail-on-cache-miss: true
      -
        uses: actions/setup-node@v4
        with:
          node-version: ${{env.node-version}}
      -
        run: npx -- eslint --color

  testing:
    runs-on: ubuntu-latest
    needs:
      - setup
    steps:
      -
        uses: actions/checkout@v4
      -
        uses: actions/cache/restore@v4
        with:
          key: pnpm-lock--${{hashFiles('pnpm-lock.yaml')}}
          path: node_modules
          fail-on-cache-miss: true
      -
        uses: actions/setup-node@v4
        with:
          node-version: ${{env.node-version}}
      -
        run: npx -- tsx --test source/index.test.ts
